CREATE TABLE `calendar` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(200) NOT NULL,
	`subject` VARCHAR(200) NOT NULL,
	`content` VARCHAR(200) NOT NULL,
	`description` VARCHAR(500) NULL DEFAULT NULL,
	`date` VARCHAR(70) NOT NULL,
	`userId` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`id`)
)
;
